// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnqpnaMqIG6SUGMPmsdkPqtIAVclTI0xc',
    appId: '1:845451996034:web:ef46a6b4bdfda0ae1e3d9b',
    messagingSenderId: '845451996034',
    projectId: 'final-project-42ecf',
    authDomain: 'final-project-42ecf.firebaseapp.com',
    storageBucket: 'final-project-42ecf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXCIaSxB2w8E7Uq2Ux9yfNJovxS0xCtQg',
    appId: '1:845451996034:android:5a56c0ac16dc48d51e3d9b',
    messagingSenderId: '845451996034',
    projectId: 'final-project-42ecf',
    storageBucket: 'final-project-42ecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_WSjXOGsNB6kbxohqH8uvAjtDgWBS5s',
    appId: '1:845451996034:ios:ba888bb0cc3ec8db1e3d9b',
    messagingSenderId: '845451996034',
    projectId: 'final-project-42ecf',
    storageBucket: 'final-project-42ecf.appspot.com',
    iosClientId: '845451996034-sp4vvqiuqjd4gep5uleopgt87sh1rhap.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_WSjXOGsNB6kbxohqH8uvAjtDgWBS5s',
    appId: '1:845451996034:ios:2c1f8b8d8e728f411e3d9b',
    messagingSenderId: '845451996034',
    projectId: 'final-project-42ecf',
    storageBucket: 'final-project-42ecf.appspot.com',
    iosClientId: '845451996034-r55n3jcnfop9hgl02i96jcueo0nv293j.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiFinalProject.RunnerTests',
  );
}
